# Generated by Django 5.0.2 on 2024-02-17 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('uom', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_net_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exw_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customs_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('my_broker', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obnal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obnal_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('quotation_number', models.CharField(max_length=50)),
                ('vat', models.CharField(max_length=50)),
                ('inco_terms', models.CharField(max_length=100)),
                ('shipment_weight', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='create_quotation',
        ),
        migrations.AddField(
            model_name='product',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.quote'),
        ),
    ]
