# Generated by Django 5.0.2 on 2024-02-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_product_quote_delete_create_quotation_product_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customs_percent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='obnal_percent',
            field=models.IntegerField(),
        ),
    ]
