# Generated by Django 5.0.2 on 2024-02-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_product_customs_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bank_charges',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customs',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customs_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='exw_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='my_broker',
        ),
        migrations.RemoveField(
            model_name='product',
            name='net_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='obnal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='obnal_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_net_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uom',
        ),
        migrations.AddField(
            model_name='product',
            name='all_info',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
