# Generated by Django 5.0.2 on 2024-02-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_product_bank_charges_remove_product_customs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
