# Generated by Django 5.0.2 on 2024-02-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
