# Generated by Django 5.0.2 on 2024-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_quote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
