# Generated by Django 5.0.2 on 2024-03-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_product_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
