# Generated by Django 5.0.2 on 2024-03-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_quote_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pre_tax_total',
            field=models.FloatField(default=0.0),
        ),
    ]
