# Generated by Django 5.0.2 on 2024-03-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_quote_pre_tax_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
    ]
