# Generated by Django 5.0.2 on 2024-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_quote_shipment_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
