# Generated by Django 5.0.2 on 2024-04-24 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_product_date_created_product_date_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, null=True)),
                ('purchase_order', models.CharField(max_length=50, null=True)),
                ('bank_details', models.CharField(max_length=2000)),
                ('director_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.quote')),
            ],
        ),
    ]
