# Generated by Django 5.0.2 on 2024-04-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_invoicemodel_buyer_name_invoicemodel_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
